<a href="https://colab.research.google.com/github/amartsin/Iris-Data-Analysis/blob/main/AttendanceProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import cv2
import numpy as np
import dlib

In [ ]:
cpip install face-recognition

In [ ]:
import face_recognition
from google.colab.patches import cv2_imshow

In [ ]:
import os

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
path = '/content/gdrive/MyDrive/FaceRecognition'
images = []
classNames =[]
mylist = os.listdir(path)
for cls in mylist:
  mlist = os.listdir(path +'/' +cls)
  path2 = f'{path}/{cls}'
  for pics in mlist:
    mlist2 = os.listdir(path2 +'/' + pics )
    path3 = f'{path2}/{pics}'
    for pic in mlist2:
      path4 = f'{path3}/{pic}'
      curImage= cv2.imread(path4)
      print(curImage)
      images.append(curImage)
      classNames.append(cls)
    
    
      
#print(images[0])  


Streaming output truncated to the last 5000 lines.
  [225 223 229]
  [227 226 230]]]
[[[30 24 25]
  [28 22 23]
  [26 20 21]
  ...
  [28 22 23]
  [30 24 25]
  [30 24 25]]

 [[27 21 22]
  [25 19 20]
  [23 17 18]
  ...
  [25 19 20]
  [26 20 21]
  [26 20 21]]

 [[26 20 21]
  [25 19 20]
  [23 17 18]
  ...
  [25 19 20]
  [25 19 20]
  [25 19 20]]

 ...

 [[30 24 25]
  [29 23 24]
  [25 19 20]
  ...
  [20 14 15]
  [21 15 16]
  [21 15 16]]

 [[24 18 19]
  [25 19 20]
  [24 18 19]
  ...
  [22 16 17]
  [27 21 22]
  [27 21 22]]

 [[18 12 13]
  [22 16 17]
  [25 19 20]
  ...
  [21 15 16]
  [27 21 22]
  [27 21 22]]]
[[[ 87  93  92]
  [ 89  95  94]
  [ 93  99  98]
  ...
  [139 145 144]
  [138 144 143]
  [137 143 142]]

 [[ 87  93  92]
  [ 90  96  95]
  [ 93  99  98]
  ...
  [139 145 144]
  [138 144 143]
  [138 144 143]]

 [[ 88  94  93]
  [ 90  96  95]
  [ 94 100  99]
  ...
  [139 145 144]
  [139 145 144]
  [138 144 143]]

 ...

 [[  4   4   4]
  [  4   4   4]
  [  4   4   4]
  ...
  [ 12  19  12]
  [ 1

KeyboardInterrupt: ignored